from typing import Any, Dict

DEFAULT_CONFIG: Dict[str, Any] = {
    "path": "./Downloaded/",
    "music": False,
    "cover": False,
    "avatar": False,
    "json": False,
    "start_time": "",
    "end_time": "",
    "folderstyle": False,
    "mode": ["post"],
    "number": {
        "post": 0,
        "like": 0,
        "allmix": 0,
        "mix": 0,
        "music": 0,
        "collect": 0,
        "collectmix": 0,
    },
    "increase": {
        "post": False,
        "like": False,
        "allmix": False,
        "mix": False,
        "music": False,
    },
    "thread": 5,
    "rate_limit": 5,
    "retry_times": 3,
    "proxy": "",
    "database": True,
    "database_path": "dy_downloader.db",
    "progress": {
        "quiet_logs": True,
    },
    "transcript": {
        "enabled": False,
        "model": "gpt-4o-mini-transcribe",
        "groq_api_key": "",
        "groq_model": "whisper-large-v3-turbo",
        "groq_max_mb": 25,
        "output_dir": "",
        "response_formats": ["txt", "json"],
        "api_url": "https://api.openai.com/v1/audio/transcriptions",
        "api_key_env": "OPENAI_API_KEY",
        "api_key": "",
    },
    "auto_cookie": False,
    "browser_fallback": {
        "enabled": True,
        "headless": False,
        "max_scrolls": 240,
        "idle_rounds": 8,
        "wait_timeout_seconds": 600,
    },
    "translation": {
        "deepseek_key": "",
        "openai_key": "",
        "hf_token": "",
        "preferred_provider": "deepseek",
        "naming_enabled": False,
    },
    "video_process": {
        "enabled": True,
        "model": "small",
        "language": "zh",
        "burn_subs": False,
        "blur_original": False,
        "translate": True,
        "burn_vi_subs": False,
        "voice_convert": True,
        "keep_bg_music": False,
        "keep_bg": False,
        "blur_zone": "bottom",
        "tts_voice": "vi-VN-HoaiMyNeural",
        "tts_engine": "edge-tts",
        "bg_volume": 0.15,
        "font_size": 18,
        "blur_height": 15,
    },
}
