from typing import Any, Dict

DEFAULT_CONFIG: Dict[str, Any] = {
    "path": "./Downloaded/",
    "music": False,
    "cover": False,
    "avatar": False,
    "json": False,
    "start_time": "",
    "end_time": "",
    "folderstyle": False,
    "mode": ["post"],
    "number": {
        "post": 0,
        "like": 0,
        "allmix": 0,
        "mix": 0,
        "music": 0,
        "collect": 0,
        "collectmix": 0,
    },
    "increase": {
        "post": False,
        "like": False,
        "allmix": False,
        "mix": False,
        "music": False,
    },
    "thread": 5,
    "rate_limit": 5,
    "retry_times": 3,
    "proxy": "",
    "database": True,
    "database_path": "dy_downloader.db",
    "progress": {
        "quiet_logs": True,
    },
    "transcript": {
        "enabled": False,
        "model": "gpt-4o-mini-transcribe",
        "groq_api_key": "",
        "groq_model": "whisper-large-v3-turbo",
        "groq_max_mb": 25,
        "output_dir": "",
        "response_formats": ["txt", "json"],
        "api_url": "https://api.openai.com/v1/audio/transcriptions",
        "api_key_env": "OPENAI_API_KEY",
        "api_key": "",
    },
    "auto_cookie": False,
    "browser_fallback": {
        "enabled": True,
        "headless": False,
        "max_scrolls": 240,
        "idle_rounds": 8,
        "wait_timeout_seconds": 600,
    },
    "translation": {
        "deepseek_key": "",
        "openai_key": "",
        "groq_key": "",
        "groq_model": "llama-3.1-8b-instant",
        "hf_token": "",
        "preferred_provider": "deepseek",
        "naming_enabled": True,
    },
    "upload": {
        "platform": "youtube",
        "auto_upload": False,
        "youtube": {
            "title_template": "{title}",
            "description_template": "{title}",
            "privacy_status": "private",
        },
        "tiktok": {
            "title_template": "{title}",
            "caption_template": "{title}",
            "privacy_status": "private",
            "scopes": ["user.info.basic", "video.publish"],
            "client_key": "",
            "client_secret": "",
            "client_key_env": "TIKTOK_CLIENT_KEY",
            "client_secret_env": "TIKTOK_CLIENT_SECRET",
            "redirect_uri": "",
        },
    },
    "ngrok": {
        "enabled": False,
        "authtoken": "",
        "domain": "",
        "bind_tls": True,
        "public_url": "",
    },
    "video_process": {
        "enabled": True,
        "model": "small",
        "language": "zh",
        "process_mode": "ai",
        "burn_subs": True,
        "blur_original": True,
        "translate": True,
        "burn_vi_subs": True,
        "voice_convert": True,
        "keep_bg_music": True,
        "keep_bg": True,
        "blur_zone": "bottom",
        "tts_voice": "vi-VN-HoaiMyNeural",
        "tts_engine": "edge-tts",
        "tts_speed": 1.0,
        "auto_speed": True,
        "pitch_semitones": 0.0,
        "fpt_api_key": "ssMeU5l89LMLfg8jhDzTBWV7D22s1xOy",
        "bg_volume": 0.15,
        "font_size": 18,
        "blur_height": 15,
        "subtitle_format": "ass",
        "subtitle_position": "bottom",
            "margin_v": 20,
            "anti_fingerprint": {
            "enabled": True,
            "overlay_image": "",
            "overlay_opacity": 0.02,
            "logo_enabled": False,
            "logo_image": "",
            "logo_position": "bottom-left",
            "logo_max_width_pct": 0.10,
            "logo_opacity": 1.0,
            "logo_padding": 10,
        },
    },
}

DEFAULT_ANTI_FINGERPRINT = {
    "enabled": True,
    "overlay_image": "",
    "overlay_opacity": 0.02,
    "logo_enabled": False,
    "logo_image": "",
    "logo_position": "bottom-left",
    "logo_max_width_pct": 0.15,
    "logo_opacity": 1.0,
    "logo_padding": 10,
}
